### ISSUE TITLE
Memory To-Do's

### ISSUE THREAD

**Issue by sethamundsen** [sethamundsen/Memory#3]
- [x] Print Boards to the screen
    - Needs a grid that separates Tiles
    - Needs a coordinate system displayed outside of the Board
- [x] Randomly generate a Board
    - Each Tile must have exactly one matching tile
    - Tiles must appear in different places each time a Board is generated
- [x] Selecting a Tile should print out the board with that Tile visible
    - If a pair of Tiles are found, update the working board so that the matched Tiles  
    - need a solution board
    - need a working board
